# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to Testing

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish --configuration Release --output publish

      - name: Create appsettings.Testing.json
        run: |
          echo '{
            "ConnectionStrings": {
              "DefaultConnection": "${{ secrets.TESTING_CONNECTION_STRING }}"
            },
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft": "Warning"
              }
            },
            "Swagger": {
              "Enable": true
            }
          }' > publish/appsettings.Testing.json

      - name: Set environment variable for EF Core
        run: echo "ASPNETCORE_ENVIRONMENT=Testing" >> $GITHUB_ENV

      - name: Apply database migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.TESTING_CONNECTION_STRING }}
        run: dotnet ef database update --project OnlineStore.WebAPI --configuration Release

      - name: Deploy using WebDeploy
        run: |
          msdeploy.exe -verb:sync -source:contentPath="publish" `
          -dest:auto,computerName="https://monsterasp.com/msdeploy.axd?site=OnlineStoreTest", `
          userName="${{ secrets.MSDEPLOY_TESTSERVER_USERNAME }}",password="${{ secrets.MSDEPLOY_TESTSERVER_PASSWORD }}"
